# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: Mark Cornick <mark@markcornick.com>

pkgname='clilol-bin'
pkgver=1.0.11
pkgrel=1
pkgdesc='A CLI for omg.lol'
url='https://clilol.readthedocs.io/'
arch=('aarch64' 'armv6h' 'i686' 'x86_64')
license=('MPL-2.0')
provides=('clilol')
conflicts=('clilol')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.11/clilol_1.0.11_linux_arm64.tar.gz")
sha256sums_aarch64=('14537161dd2a90f45db79966b5fad386a0dff10b91d7a14bd330d4fd109768ee')

source_armv6h=("${pkgname}_${pkgver}_armv6h.tar.gz::https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.11/clilol_1.0.11_linux_armv6.tar.gz")
sha256sums_armv6h=('b7b45ee4229df455099dbd29da4335235a911483d14dc8f9b0376e307dc6c083')

source_i686=("${pkgname}_${pkgver}_i686.tar.gz::https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.11/clilol_1.0.11_linux_386.tar.gz")
sha256sums_i686=('2661ce639015383758607269c35c403b08e6d7f6a5b8d7a0a7d4035a8289d652')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.11/clilol_1.0.11_linux_amd64.tar.gz")
sha256sums_x86_64=('8b741f3e73bcb323e7d08e8f3d6ff22922fde2c9f4ec21d9dcedb81fff1b1b09')

package() {
  install -Dm755 "./clilol" "${pkgdir}/usr/bin/clilol"
  install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clilol/LICENSE"
  mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
  mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
  mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
  install -Dm644 "./completions/clilol.bash" "${pkgdir}/usr/share/bash-completion/completions/clilol"
  install -Dm644 "./completions/clilol.zsh" "${pkgdir}/usr/share/zsh/site-functions/_clilol"
  install -Dm644 "./completions/clilol.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/clilol.fish"
  install -Dm644 "./manpages/*.1" "${pkgdir}/usr/share/man/man1/*.1"
}
