# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: Mark Cornick <mark@markcornick.com>

pkgname='clilol-bin'
pkgver=1.1.1
pkgrel=1
pkgdesc='A CLI for omg.lol'
url='https://clilol.readthedocs.io/'
arch=('aarch64' 'i686' 'x86_64')
license=('MPL-2.0')
provides=('clilol')
conflicts=('clilol')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/mcornick/clilol/releases/download/v1.1.1/clilol_1.1.1_linux_arm64.tar.gz")
sha256sums_aarch64=('145af72a601b9478da0ddd82ca330d284d94ddaf3e4dc1206e4d643ddfffbe99')

source_i686=("${pkgname}_${pkgver}_i686.tar.gz::https://github.com/mcornick/clilol/releases/download/v1.1.1/clilol_1.1.1_linux_386.tar.gz")
sha256sums_i686=('9527799d1f0af257d58a71e7564aa82666c19b2173c4928cca46ee671204c2d5')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/mcornick/clilol/releases/download/v1.1.1/clilol_1.1.1_linux_amd64.tar.gz")
sha256sums_x86_64=('309dea76e2bba08dd890075eb4d18649ab9e4904df91c186a4605d26a671106a')

package() {
  install -Dm755 "./clilol" "${pkgdir}/usr/bin/clilol"
  install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clilol/LICENSE"
  mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
  mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
  mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
  install -Dm644 "./completions/clilol.bash" "${pkgdir}/usr/share/bash-completion/completions/clilol"
  install -Dm644 "./completions/clilol.zsh" "${pkgdir}/usr/share/zsh/site-functions/_clilol"
  install -Dm644 "./completions/clilol.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/clilol.fish"
  install -Dm644 "./manpages/clilol.1" "${pkgdir}/usr/share/man/man1/clilol.1"

}
