# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: Mark Cornick <mcornick@mcornick.com>

pkgname='clilol-bin'
pkgver=0.5.3
pkgrel=1
pkgdesc='A CLI for omg.lol'
url='https://mcornick.com/clilol/'
arch=('aarch64' 'armv6h' 'i686' 'x86_64')
license=('MPL-2.0')
provides=('clilol')
conflicts=('clilol')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/mcornick/clilol/releases/download/v0.5.3/clilol_0.5.3_linux_arm64.tar.gz")
sha256sums_aarch64=('3d16057754fbbae71bcb26ce0c90a21d1cba4afe4547eb5daaa3815156ee5df6')

source_armv6h=("${pkgname}_${pkgver}_armv6h.tar.gz::https://github.com/mcornick/clilol/releases/download/v0.5.3/clilol_0.5.3_linux_armv6.tar.gz")
sha256sums_armv6h=('b8dcd034276dd215d025a156797f259b58a23d6576c0f9f699a88295b22fb71d')

source_i686=("${pkgname}_${pkgver}_i686.tar.gz::https://github.com/mcornick/clilol/releases/download/v0.5.3/clilol_0.5.3_linux_386.tar.gz")
sha256sums_i686=('f000a5dec29207335540c2a03b1805f3e9c0ddcbc34d08a28454e86f039825cb')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/mcornick/clilol/releases/download/v0.5.3/clilol_0.5.3_linux_amd64.tar.gz")
sha256sums_x86_64=('3ca026c029e81dfd5ecd780fc9edc2374c8998ff928138194d6cfb79d74e099e')

package() {
  install -Dm755 "./clilol" "${pkgdir}/usr/bin/clilol"
  install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clilol/LICENSE"
  mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
  mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
  mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
  install -Dm644 "./completions/clilol.bash" "${pkgdir}/usr/share/bash-completion/completions/clilol"
  install -Dm644 "./completions/clilol.zsh" "${pkgdir}/usr/share/zsh/site-functions/_clilol"
  install -Dm644 "./completions/clilol.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/clilol.fish"
  install -Dm644 "./manpages/*.1" "${pkgdir}/usr/share/man/man1/*.1"
}
